---
title: 'Peer-graded Assignment: Getting and Cleaning Data Course Project'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r }

library(dplyr)

filename <- "Coursera_DS3_Final.zip"

# Checking if archieve already exists.
if (!file.exists(filename)){
  fileURL <- "https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip"
  download.file(fileURL, filename, method="curl")
}  

# Checking if folder exists
if (!file.exists("UCI HAR Dataset")) { 
  unzip(filename) 
}

# Load activity labels + features
#Read Supporting Metadata
features <- read.table("UCI HAR Dataset/features.txt", col.names = c("n","functions"))
activities <- read.table("UCI HAR Dataset/activity_labels.txt", col.names = c("code", "activity"))

#Read test data

subject_test <- read.table("UCI HAR Dataset/test/subject_test.txt", col.names = "subject")
x_test <- read.table("UCI HAR Dataset/test/X_test.txt", col.names = features$functions)
y_test <- read.table("UCI HAR Dataset/test/y_test.txt", col.names = "code")

#Read training data
subject_train <- read.table("UCI HAR Dataset/train/subject_train.txt", col.names = "subject")
x_train <- read.table("UCI HAR Dataset/train/X_train.txt", col.names = features$functions)
y_train <- read.table("UCI HAR Dataset/train/y_train.txt", col.names = "code")

#1 Merges the training and the test sets to create one data set.
xbind <- rbind(x_train, x_test)
ybind <- rbind(y_train, y_test)
subjectbind <- rbind(subject_train, subject_test)
Merged_Data <- cbind(subjectbind, xbind, ybind)

#2 Extracts only the measurements on the mean and standard deviation for each measurement.
extracteddata <- Merged_Data %>% select(subject, code, contains("mean"), contains("std"))

#3 Uses descriptive activity names to name the activities in the data set
extracteddata$code <- activities[extracteddata$code, 2]


# Part 4 - Appropriately labels the data set with descriptive variable names
names(extracteddata)[2] = "activity"
names(extracteddata)<-gsub("Acc", "accelerometer", names(extracteddata))
names(extracteddata)<-gsub("angle", "angle", names(extracteddata))
names(extracteddata)<-gsub("BodyBody", "body", names(extracteddata))
names(extracteddata)<-gsub("^f", "frequency", names(extracteddata))
names(extracteddata)<-gsub("-freq()", "frequency", names(extracteddata), ignore.case = TRUE)
names(extracteddata)<-gsub("gravity", "gravity", names(extracteddata))
names(extracteddata)<-gsub("Gyro", "gyroscope", names(extracteddata))
names(extracteddata)<-gsub("Mag", "magnitude", names(extracteddata))
names(extracteddata)<-gsub("-mean()", "mean", names(extracteddata), ignore.case = TRUE)
names(extracteddata)<-gsub("^t", "time", names(extracteddata))
names(extracteddata)<-gsub("tBody", "timebody", names(extracteddata))
names(extracteddata)<-gsub("-std()", "STD", names(extracteddata), ignore.case = TRUE)

#5 From the data set in step 4, creates a second, independent tidy data set with the average of each variable for each activity and each subject.
step5data <- extracteddata %>%
    group_by(subject, activity) %>%
    summarise_all(funs(mean))
write.table(step5data, "tidy.txt", row.name=FALSE)


```